name: Docker

on:
  workflow_call:

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Build
      uses: docker/setup-buildx-action@v3.6.1

    - name: Log in DockerHub
      uses: docker/login-action@v3.3.0
      with:
      #This will work now
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push Docker images
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: raphaelftsantos/go_ci:${{github.ref_name}}